### PR TITLE
remove the last semi-colon

### PR DESCRIPTION
**Pull request by i3luefire**
the last semi-colon breaks the script

### CODE REVIEW

**Comment by NitrogenUA** [comment]
Can you please let us know what kind of error you are facing? And also what software you run it on? I thought it was an unintentional mistake and added that semicolon in my latest commit. But it works for me regardless. I run the script on Debian 8/Apache/PHP5.6.

**Comment by i3luefire** [comment]
I am running it on nginx, with php7.1, on FreeBSD 11.1 and I was getting a 500 error I believe. 

I can add the semicolon back tonight to reproduce the problem again if that helps.

**Comment by NitrogenUA** [comment]
For now I can suggest uncommenting error reporting lines in minerstats.php(currently lines 2 and 3), which might provide more useful insight into the issue. For instance I had to discover through trial and error that you can not leave $crypto variable empty because that makes the script fail. Error reporting however did not report my own syntax typos, which might be relevant if you made changes to the code yourself.

**Comment by i3luefire** [comment]
I added the semicolon back and everything still worked. Sorry for the confusion. I am not really a programmer so I really should not do things like this. 

I am not sure what the original problem was now. 

Sorry for wasting your time.

**Pull request closed without merging**
